// scripts/genLevels.mjs
// Parse gdd/*.csv → validate → write src/data/levelOverrides.generated.js (committed).
// A missing level row is fine (that level keeps its code defaults); bad data fails loudly.
//   npm run gen:levels
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RAW_LEVELS } from '../src/data/leveldata.js';
import {
  parseLevelsCsv, parseDesignsCsv, KNOWN_VEHICLE_TYPES, KNOWN_SIZES,
} from '../src/data/levelKnobs.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const gddDir = resolve(__dirname, '../gdd');
const levelsPath = resolve(gddDir, 'levels.csv');
const designsPath = resolve(gddDir, 'vehicle_designs.csv');
const outPath = resolve(__dirname, '../src/data/levelOverrides.generated.js');

if (!existsSync(levelsPath)) {
  console.error(`Missing ${levelsPath} — run \`npm run export:levels\` first.`);
  process.exit(1);
}

const levelKnobs = parseLevelsCsv(readFileSync(levelsPath, 'utf8'));
const designs = existsSync(designsPath) ? parseDesignsCsv(readFileSync(designsPath, 'utf8')) : {};

const errors = [];
for (const [id, k] of Object.entries(levelKnobs)) {
  if (!RAW_LEVELS[id]) errors.push(`levels.csv: unknown level id "${id}"`);
  for (const t of k.vehicles ?? []) {
    if (!KNOWN_VEHICLE_TYPES.includes(t)) errors.push(`${id}: unknown vehicle type "${t}"`);
  }
  for (const s of [...(k.roadSizes ?? []), ...(k.woodSizes ?? [])]) {
    if (!KNOWN_SIZES.includes(s)) errors.push(`${id}: unknown block size "${s}"`);
  }
  if (designs[id]) {
    k.designs = designs[id];
    for (const t of Object.keys(designs[id])) {
      if (!KNOWN_VEHICLE_TYPES.includes(t)) errors.push(`${id}: design for unknown type "${t}"`);
    }
  }
}
for (const id of Object.keys(designs)) {
  if (!RAW_LEVELS[id]) errors.push(`vehicle_designs.csv: unknown level id "${id}"`);
}

if (errors.length) {
  console.error('CSV validation failed:\n' + errors.map(e => '  - ' + e).join('\n'));
  process.exit(1);
}

const body = `// AUTO-GENERATED by scripts/genLevels.mjs from gdd/levels.csv + gdd/vehicle_designs.csv.
// Do NOT edit by hand — run \`npm run gen:levels\` to regenerate.
export const LEVEL_OVERRIDES = ${JSON.stringify(levelKnobs, null, 2)};
`;
writeFileSync(outPath, body);
console.log(`Wrote ${outPath} (${Object.keys(levelKnobs).length} levels).`);
